version: "3.9"
services:
  velociraptor:
    container_name: velociraptor
    #image: wlambert/velociraptor
    build:
      context: ./velociraptor
      dockerfile: Dockerfile
    volumes:
      - ./velociraptor_data:/velociraptor/:rw
      - ./velociraptor/custom:/custom:ro
      - ./velociraptor/entrypoint:/entrypoint:ro
      - velo_api:/api/
    environment:
      - VELO_USER=${VELO_USER}
      - VELO_PASSWORD=${VELO_PASSWORD}
      - VELO_ROLE=${VELO_ROLE}
      - VELO_SERVER_URL=${VELO_SERVER_URL}
      - VELO_FRONTEND_HOSTNAME=${VELO_FRONTEND_HOSTNAME}
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8889:8889"
volumes:
  velo_api:
